import { cleanup } from '@testing-library/vue'
import { afterAll, afterEach, beforeAll } from 'vitest'

import { installTestLanguage } from '@/shared/i18n/i18n'

import { server } from './server'

installTestLanguage(
  {
    'access.registration.title': 'Claim this machine',
    'access.signedOut.title': 'Return to Nox',
    'auth.field.claimCode': 'Claim code',
    'auth.field.confirmPassword': 'Confirm password',
    'auth.field.identity': 'Identity',
    'auth.field.password': 'Password',
    'auth.login.submit': 'Enter Nox',
    'auth.registration.claimCodeHint': 'Claim code hint',
    'auth.registration.confirmPasswordPlaceholder': 'Repeat your password',
    'auth.registration.identityHint': 'Identity hint',
    'auth.registration.passwordPlaceholder': '8 characters minimum',
    'auth.registration.submit': 'Claim',
    'audit.detail.attribution': 'Attribution',
    'audit.detail.decision': 'Decision path',
    'audit.detail.eyebrow': 'DECISION RECORD',
    'audit.detail.humanResolution': 'Human resolution',
    'audit.detail.noSelection': 'Select a decision',
    'audit.detail.noSelectionBody': 'Choose a decision.',
    'audit.detail.outcome': 'Observed outcome',
    'audit.detail.request': 'Requested capability',
    'audit.detail.risk': 'Risk surface',
    'audit.effect.network': 'Network',
    'audit.effect.write': 'Write',
    'audit.empty.body': 'Capability decisions will appear here.',
    'audit.empty.title': 'No decisions found',
    'audit.explorer': 'Decision explorer',
    'audit.eyebrow': 'SECURITY // DECISION LEDGER',
    'audit.field.agent': 'Agent',
    'audit.field.authority': 'Authority',
    'audit.field.completedAt': 'Observed at',
    'audit.field.decidedBy': 'Evaluator',
    'audit.field.effects': 'Effects',
    'audit.field.outcome': 'Result',
    'audit.field.parameters': 'Parameters',
    'audit.field.preview': 'Preview',
    'audit.field.principal': 'Principal',
    'audit.field.reason': 'Reason',
    'audit.field.requestedAt': 'Requested at',
    'audit.field.resolution': 'Resolution',
    'audit.field.resolvedAt': 'Resolved at',
    'audit.field.resolvedBy': 'Resolved by',
    'audit.field.resources': 'Resources',
    'audit.field.reversible': 'Reversible',
    'audit.field.run': 'Run',
    'audit.field.scope': 'Approval scope',
    'audit.field.session': 'Session',
    'audit.field.stage': 'Stage',
    'audit.field.tool': 'Tool',
    'audit.field.track': 'Track',
    'audit.filter.all': 'All',
    'audit.filter.apply': 'Apply filters',
    'audit.filter.clear': 'Clear',
    'audit.filter.query': 'Search ledger',
    'audit.filter.queryPlaceholder': 'Tool, agent, session, authority…',
    'audit.filter.resolution': 'Resolution',
    'audit.filter.stage': 'Stage',
    'audit.filter.verdict': 'Verdict',
    'audit.list.label': 'Audit decisions',
    'audit.outcome.completed': 'Tool completed',
    'audit.outcome.deferred': 'Deferred work acknowledged',
    'audit.outcome.failed': 'Tool failed',
    'audit.outcome.notObserved': 'No tool result was recorded',
    'audit.outcome.permissionPending': 'Permission requested; execution not observed',
    'audit.output.artifact': 'Artifact',
    'audit.output.artifactId': 'Artifact ID',
    'audit.output.empty': 'The tool returned no content.',
    'audit.output.mediaType': 'Media type',
    'audit.response.immediate': 'Immediate result',
    'audit.response.permissionPending': 'Permission request',
    'audit.trust.trusted': 'Trusted output',
    'audit.trust.untrusted': 'Untrusted output',
    'audit.pagination.next': 'Next',
    'audit.pagination.page': 'Page {current} of {total}',
    'audit.pagination.previous': 'Previous',
    'audit.resolution.aborted': 'Aborted',
    'audit.resolution.approved': 'Approved',
    'audit.resolution.denied': 'Denied',
    'audit.resolution.timeout': 'Timed out',
    'audit.scope.once': 'This call only',
    'audit.scope.session': 'Entire session',
    'audit.stage.authorization': 'Authorization',
    'audit.stage.gate': 'Risk gate',
    'audit.state.loading': 'Reading ledger',
    'audit.state.records': '{count} records',
    'audit.status.allowed': 'Allowed',
    'audit.status.approved': 'Approved',
    'audit.status.pending': 'Pending approval',
    'audit.subtitle': 'Why capabilities were allowed, escalated, or stopped.',
    'audit.title': 'Audit',
    'audit.value.unknownAgent': 'Unattributed agent',
    'audit.verdict.allow': 'Allow',
    'audit.verdict.deny': 'Deny',
    'audit.verdict.escalate': 'Escalate',
    'chat.activity.completed': 'Run completed',
    'chat.context.capacityUnknown':
      'Context uses approximately {used} tokens; model capacity is unknown',
    'chat.context.full':
      'Context {percentage} percent full: approximately {used} of {capacity} tokens',
    'chat.context.tokens': '{count} tokens',
    'chat.context.window': 'Context window',
    'chat.conversation.find': 'Find a conversation',
    'chat.conversation.noMatches': 'No matching conversations.',
    'chat.conversation.searchPlaceholder': 'Search conversations…',
    'chat.message.responseProcess': 'Response process',
    'chat.message.steer': 'STEER · RESPONSE REDIRECTED',
    'chat.tool.arguments': 'Arguments',
    'chat.tool.error': 'error',
    'chat.tool.failed': 'failed',
    'chat.tool.result': 'Result',
    'common.add': 'Add',
    'common.details': 'Details',
    'common.discard': 'Discard',
    'common.missing': 'missing',
    'common.remove': 'Remove',
    'common.requiredShort': 'REQ',
    'navigation.sessions': 'Sessions',
    'navigation.settings': 'Settings',
    'nox.provider.openai.ui.apiCredential': 'API credential',
    'nox.provider.openai.ui.contextWindow': 'Context window',
    'nox.provider.openai.ui.inputModalities': 'Accepted input modalities',
    'nox.provider.openai.ui.modelId': 'Model ID',
    'nox.provider.openai.ui.newManagedSecret': 'New managed secret',
    'nox.provider.openai.ui.newSecretId': 'New secret ID',
    'nox.provider.openai.ui.newSecretValue': 'New secret value',
    'nox.provider.openai.ui.openaiCompletions': 'OpenAI-compatible completions',
    'nox.provider.openai.ui.outputModalities': 'Generated output modalities',
    'nox.toolset.web.ui.credential': 'Credential',
    'nox.toolset.web.ui.defaultResults': 'Default results',
    'nox.toolset.web.ui.maximumUrls': 'Maximum URLs per call',
    'nox.toolset.web.ui.serviceUrl': 'Service URL',
    'nox.toolset.web.ui.slot.browser': 'Browser',
    'nox.toolset.web.ui.slot.extract': 'Extraction',
    'nox.toolset.web.ui.slot.search': 'Search',
    'sessions.agent.current': 'CURRENT AGENT',
    'sessions.agent.label': 'Agent',
    'sessions.agent.sessionCount': '{count} sessions',
    'sessions.agent.unattributed': 'Unattributed historical sessions',
    'sessions.back': 'Back to sessions',
    'sessions.empty.agentsBody': 'Sessions will appear after the first conversation.',
    'sessions.empty.agentsTitle': 'No historical sessions',
    'sessions.empty.auditBody': 'This session contains no capability decisions.',
    'sessions.empty.auditTitle': 'No audited actions',
    'sessions.empty.sessionsBody': 'This agent has no stored conversations.',
    'sessions.empty.sessionsTitle': 'No sessions for this agent',
    'sessions.empty.transcriptBody': 'No messages were stored for this session.',
    'sessions.empty.transcriptTitle': 'Empty conversation',
    'sessions.eyebrow': 'HISTORY // STORED CONVERSATIONS',
    'sessions.open': 'Open session',
    'sessions.state.archived': 'Stored session',
    'sessions.state.count': '{count} sessions',
    'sessions.state.loading': 'Reading sessions',
    'sessions.state.loadingSession': 'Opening session',
    'sessions.subtitle': 'Open a conversation to inspect it.',
    'sessions.tabs.audit': 'Audit',
    'sessions.tabs.conversation': 'Conversation',
    'sessions.tabs.label': 'Session views',
    'sessions.title': 'Sessions',
    'sessions.transcript.complete': 'complete',
    'sessions.transcript.failed': 'failed',
    'sessions.transcript.label': 'Stored conversation transcript',
    'sessions.transcript.role.assistant': 'Assistant',
    'sessions.transcript.role.compacted': 'Compacted context',
    'sessions.transcript.role.folded': 'Folded context',
    'sessions.transcript.role.reasoning': 'Reasoning',
    'sessions.transcript.role.toolCall': 'Tool call',
    'sessions.transcript.role.toolResponse': 'Tool response',
    'sessions.transcript.role.user': 'User',
    'sessions.untitled': 'Untitled session',
    'settings.agent.description': 'Description',
    'settings.agent.direct': 'Direct',
    'settings.agent.model': 'Model',
    'settings.agent.moveFrom': 'MOVE FROM {channel}',
    'settings.agent.noChannelCapabilities.direct':
      'No direct capabilities. Use + Add to grant one.',
    'settings.agent.noChannelCapabilities.routed':
      'No routed capabilities. Use + Add to grant one.',
    'settings.agent.provider': 'Provider',
    'settings.agent.routed': 'Routed',
    'settings.agent.save': 'Save agent',
    'settings.agent.saved': 'Agent blueprint saved',
    'settings.agent.searchToolSets': 'Search configured Tool Sets',
    'settings.agent.selectedTools': 'Selected tools',
    'settings.agent.systemPromptPlaceholder': 'You are...',
    'settings.broker.baseAgent': 'Base agent',
    'settings.broker.save': 'Save broker',
    'settings.broker.saved': 'Broker configuration saved',
    'settings.editor.advancedSurface': 'ADVANCED SURFACE',
    'settings.editor.form': 'Form',
    'settings.editor.formatDocument': 'Format document',
    'settings.editor.hotApply': 'HOT APPLY',
    'settings.editor.json': 'JSON',
    'settings.editor.jsonObject': 'JSON object',
    'settings.editor.mixedApply': 'HOT + RESTART-SCOPED',
    'settings.editor.savedImmediate': 'Nox reconciled this change without requiring a restart.',
    'settings.editor.savedRestart': 'Restart Nox to activate this infrastructure change.',
    'settings.entries.emptyContributed':
      'This section is loaded, but no active extension has contributed an entry.',
    'settings.general.accessTtl': 'Access token TTL (seconds)',
    'settings.general.artifactSizeLimit': 'Maximum artifact bytes',
    'settings.general.artifactSizeLimitHint': 'Maximum artifact hint',
    'settings.general.artifactStorageQuota': 'Artifact storage quota',
    'settings.general.artifactStorageQuotaHint': 'Artifact quota hint',
    'settings.general.bindHost': 'Bind host',
    'settings.general.databasePath': 'Database path',
    'settings.general.httpPort': 'HTTP port',
    'settings.general.interface': 'INTERFACE',
    'settings.general.interfaceLanguage': 'Interface language',
    'settings.general.interfaceLanguageHelp': 'Choose the installation language.',
    'settings.general.locale': 'Default language',
    'settings.general.localeHint': 'Applied immediately.',
    'settings.general.logLevel': 'Log level',
    'settings.general.save': 'Save general settings',
    'settings.general.timezone': 'Time zone',
    'settings.general.validation.artifactStorageQuota':
      'Storage quota must hold one artifact.',
    'settings.general.validation.timezone':
      'Use an IANA time zone name, such as UTC or America/Mexico_City.',
    'settings.runtime.degraded': 'Runtime configuration needs attention',
    'settings.runtime.degradedHelp': 'Desired configuration did not fully activate.',
    'settings.runtime.reload': 'Reload mounted config',
    'settings.runtime.restartRequired': 'Restart required',
    'settings.runtime.restartRequiredHelp': 'Infrastructure changes activate on restart.',
    'settings.runtime.retry': 'Retry activation',
    'settings.runtime.revert': 'Revert failed change',
    'settings.runtime.unavailable': 'Unavailable',
    'settings.general.saved': 'Application configuration saved',
    'settings.general.secureCookies': 'Secure refresh cookies',
    'settings.group.capabilities': 'CAPABILITIES',
    'settings.group.intelligence': 'INTELLIGENCE',
    'settings.group.machine': 'MACHINE',
    'settings.group.security': 'SECURITY',
    'settings.provider.id': 'Provider ID',
    'settings.provider.remove': 'Remove provider',
    'settings.provider.save': 'Save provider',
    'settings.provider.saved': 'Provider configuration saved',
    'settings.provider.titleNew': 'New provider',
    'settings.sections.agents.plural': 'Agents',
    'settings.sections.brokers.plural': 'Brokers',
    'settings.sections.general.label': 'General',
    'settings.sections.general.plural': 'General',
    'settings.sections.providers.plural': 'Providers',
    'settings.sections.secrets.plural': 'Secrets',
    'settings.sections.toolSets.plural': 'Tool Sets',
    'settings.secrets.newValue': 'New value',
    'settings.secrets.replaceValue': 'Replace value',
    'settings.secrets.stored': 'STORED',
    'settings.secrets.storeStatus': 'STORE STATUS',
    'settings.secrets.valuePlaceholder': 'Value will not be shown again',
    'settings.toolSet.capabilitySurface': 'Capability surface',
    'settings.toolSet.configured': 'CONFIGURED',
    'settings.toolSet.credentialValue': 'Credential value',
    'settings.toolSet.disabled': 'DISABLED',
    'settings.toolSet.enableSlot': 'Enable this section to configure it.',
    'settings.toolSet.exposed': 'EXPOSED',
    'settings.toolSet.held': 'HELD',
    'settings.toolSet.id': 'Tool-set ID',
    'settings.toolSet.newManagedSecret': 'New managed secret',
    'settings.toolSet.newSecretId': 'New secret ID',
    'settings.toolSet.noCredential': 'No credential',
    'settings.toolSet.remove': 'Remove tool set',
    'settings.toolSet.save': 'Save tool set',
    'settings.toolSet.saved': 'Tool-set configuration saved',
    'settings.toolSet.slotOffline': 'NOT CONFIGURED',
    'settings.toolSet.surface': 'SURFACE',
    'settings.toolSet.toolSetJson': 'Tool-set JSON',
    'settings.validation.integerRange': 'Use a whole number from {minimum} to {maximum}.',
  },
  'en',
  ['es'],
)

beforeAll(() => {
  server.listen({ onUnhandledRequest: 'error' })
})

afterEach(() => {
  cleanup()
  server.resetHandlers()
})

afterAll(() => {
  server.close()
})
