import { cleanup } from '@testing-library/vue'
import { afterAll, afterEach, beforeAll } from 'vitest'

import { installTestLanguage } from '@/shared/i18n/i18n'

import { server } from './server'

installTestLanguage(
  {
    'access.registration.title': 'Claim this machine',
    'access.signedOut.title': 'Return to Nox',
    'auth.field.claimCode': 'Claim code',
    'auth.field.confirmPassword': 'Confirm password',
    'auth.field.identity': 'Identity',
    'auth.field.password': 'Password',
    'auth.login.submit': 'Enter Nox',
    'auth.registration.claimCodeHint': 'Claim code hint',
    'auth.registration.confirmPasswordPlaceholder': 'Repeat your password',
    'auth.registration.identityHint': 'Identity hint',
    'auth.registration.passwordPlaceholder': '8 characters minimum',
    'auth.registration.submit': 'Claim this Nox',
    'chat.activity.completed': 'Run completed',
    'chat.context.capacityUnknown':
      'Context uses approximately {used} tokens; model capacity is unknown',
    'chat.context.full':
      'Context {percentage} percent full: approximately {used} of {capacity} tokens',
    'chat.context.tokens': '{count} tokens',
    'chat.context.window': 'Context window',
    'chat.conversation.find': 'Find a conversation',
    'chat.conversation.noMatches': 'No matching conversations.',
    'chat.conversation.searchPlaceholder': 'Search conversations…',
    'chat.message.responseProcess': 'Response process',
    'chat.message.steer': 'STEER · RESPONSE REDIRECTED',
    'chat.tool.arguments': 'Arguments',
    'chat.tool.error': 'error',
    'chat.tool.failed': 'failed',
    'chat.tool.result': 'Result',
    'common.add': 'Add',
    'common.details': 'Details',
    'common.discard': 'Discard',
    'common.missing': 'missing',
    'common.remove': 'Remove',
    'common.requiredShort': 'REQ',
    'navigation.settings': 'Settings',
    'nox.provider.openai.ui.apiCredential': 'API credential',
    'nox.provider.openai.ui.contextWindow': 'Context window',
    'nox.provider.openai.ui.inputModalities': 'Accepted input modalities',
    'nox.provider.openai.ui.modelId': 'Model ID',
    'nox.provider.openai.ui.newManagedSecret': 'New managed secret',
    'nox.provider.openai.ui.newSecretId': 'New secret ID',
    'nox.provider.openai.ui.newSecretValue': 'New secret value',
    'nox.provider.openai.ui.openaiCompletions': 'OpenAI-compatible completions',
    'nox.provider.openai.ui.outputModalities': 'Generated output modalities',
    'nox.toolset.web.ui.credential': 'Credential',
    'nox.toolset.web.ui.defaultResults': 'Default results',
    'nox.toolset.web.ui.maximumUrls': 'Maximum URLs per call',
    'nox.toolset.web.ui.serviceUrl': 'Service URL',
    'nox.toolset.web.ui.slot.browser': 'Browser',
    'nox.toolset.web.ui.slot.extract': 'Extraction',
    'nox.toolset.web.ui.slot.search': 'Search',
    'settings.agent.defaultAgent': 'DEFAULT AGENT',
    'settings.agent.description': 'Description',
    'settings.agent.direct': 'Direct',
    'settings.agent.model': 'Model',
    'settings.agent.moveFrom': 'MOVE FROM {channel}',
    'settings.agent.noChannelCapabilities.direct':
      'No direct capabilities. Use + Add to grant one.',
    'settings.agent.noChannelCapabilities.routed':
      'No routed capabilities. Use + Add to grant one.',
    'settings.agent.provider': 'Provider',
    'settings.agent.routed': 'Routed',
    'settings.agent.save': 'Save agent',
    'settings.agent.saved': 'Agent blueprint saved',
    'settings.agent.searchToolSets': 'Search configured Tool Sets',
    'settings.agent.selectedTools': 'Selected tools',
    'settings.agent.systemPromptPlaceholder': 'You are...',
    'settings.broker.baseAgent': 'Base agent',
    'settings.broker.contributionJson': 'Contribution JSON',
    'settings.broker.newValuePlaceholder': 'New value for {secret}',
    'settings.broker.save': 'Save broker',
    'settings.broker.saved': 'Broker configuration saved',
    'settings.editor.advancedSurface': 'ADVANCED SURFACE',
    'settings.editor.form': 'Form',
    'settings.editor.formatDocument': 'Format document',
    'settings.editor.json': 'JSON',
    'settings.editor.jsonObject': 'JSON object',
    'settings.entries.emptyContributed':
      'This section is loaded, but no active extension has contributed an entry.',
    'settings.general.accessTtl': 'Access token TTL (seconds)',
    'settings.general.artifactSizeLimit': 'Maximum artifact bytes',
    'settings.general.artifactSizeLimitHint': 'Maximum artifact hint',
    'settings.general.artifactStorageQuota': 'Artifact storage quota',
    'settings.general.artifactStorageQuotaHint': 'Artifact quota hint',
    'settings.general.bindHost': 'Bind host',
    'settings.general.databasePath': 'Database path',
    'settings.general.defaultAgent': 'Default agent',
    'settings.general.httpPort': 'HTTP port',
    'settings.general.interface': 'INTERFACE',
    'settings.general.interfaceLanguage': 'Interface language',
    'settings.general.interfaceLanguageHelp': 'Choose the installation language.',
    'settings.general.locale': 'Default language',
    'settings.general.localeHint': 'Applied immediately and saved on restart.',
    'settings.general.logLevel': 'Log level',
    'settings.general.save': 'Save general settings',
    'settings.general.timezone': 'Time zone',
    'settings.general.validation.artifactStorageQuota':
      'Storage quota must hold one artifact.',
    'settings.general.validation.timezone':
      'Use an IANA time zone name, such as UTC or America/Mexico_City.',
    'settings.general.saved': 'Application configuration saved',
    'settings.general.secureCookies': 'Secure refresh cookies',
    'settings.group.capabilities': 'CAPABILITIES',
    'settings.group.intelligence': 'INTELLIGENCE',
    'settings.group.machine': 'MACHINE',
    'settings.group.security': 'SECURITY',
    'settings.provider.id': 'Provider ID',
    'settings.provider.remove': 'Remove provider',
    'settings.provider.save': 'Save provider',
    'settings.provider.saved': 'Provider configuration saved',
    'settings.provider.titleNew': 'New provider',
    'settings.sections.agents.plural': 'Agents',
    'settings.sections.brokers.plural': 'Brokers',
    'settings.sections.general.label': 'General',
    'settings.sections.general.plural': 'General',
    'settings.sections.providers.plural': 'Providers',
    'settings.sections.secrets.plural': 'Secrets',
    'settings.sections.toolSets.plural': 'Tool Sets',
    'settings.secrets.newValue': 'New value',
    'settings.secrets.replaceValue': 'Replace value',
    'settings.secrets.stored': 'STORED',
    'settings.secrets.storeStatus': 'STORE STATUS',
    'settings.secrets.valuePlaceholder': 'Value will not be shown again',
    'settings.toolSet.capabilitySurface': 'Capability surface',
    'settings.toolSet.configured': 'CONFIGURED',
    'settings.toolSet.credentialValue': 'Credential value',
    'settings.toolSet.disabled': 'DISABLED',
    'settings.toolSet.enableSlot': 'Enable this section to configure it.',
    'settings.toolSet.exposed': 'EXPOSED',
    'settings.toolSet.held': 'HELD',
    'settings.toolSet.id': 'Tool-set ID',
    'settings.toolSet.newManagedSecret': 'New managed secret',
    'settings.toolSet.newSecretId': 'New secret ID',
    'settings.toolSet.noCredential': 'No credential',
    'settings.toolSet.remove': 'Remove tool set',
    'settings.toolSet.save': 'Save tool set',
    'settings.toolSet.saved': 'Tool-set configuration saved',
    'settings.toolSet.slotOffline': 'NOT CONFIGURED',
    'settings.toolSet.surface': 'SURFACE',
    'settings.toolSet.toolSetJson': 'Tool-set JSON',
    'settings.toolSet.type': 'Tool-set type',
    'settings.validation.integerRange': 'Use a whole number from {minimum} to {maximum}.',
  },
  'en',
  ['es'],
)

beforeAll(() => {
  server.listen({ onUnhandledRequest: 'error' })
})

afterEach(() => {
  cleanup()
  server.resetHandlers()
})

afterAll(() => {
  server.close()
})
